---
- hosts: controller
  become: yes
  gather_facts: yes

  tasks:
  - name: Installing packages 
    include: play/install_pkg.yml
   
  - name: Mariadb and service
    include: play/mariadb.yml
  
  - name: Rabbimq installation and configuration
    include: play/rabbitmq.yml

  - name: Memcached install and configure
    include: play/memcache.yml

